#!/bin/python
# -*- coding: utf-8 -*-

# simple daemon that digitalize speaker bells/ beeps (char 7)
# By Chrys, Storm Dragon, and contributers.

import os, sys
import __main__

if not os.path.dirname(os.path.realpath(__main__.__file__)) in sys.path:
    sys.path.append(os.path.dirname(os.path.realpath(__main__.__file__)))

import palimpalim

def main():
    app = palimpalim.palimpalim()
    app.proceed()
    del app

if __name__ == "__main__":
    main()     
